version: '3'
services:
  grib2json-docker:
    image: grib2json-docker
    command: grib2json --names --data --fp 2 --fs 103 --fv 10.0 --output /usr/local/data/outputdata.json /usr/local/data/harmonie_skandinavia_pinta_20180725T000000_20180725T000000_20180725T000000_latlon.grb2
    volumes:
      - .:/usr/local/data  

